server:
  port: 8083

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #单个文件的大小限制
      max-request-size: 22MB #多个文件的大小限制

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl