server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true #在sprigboot2.1之前默认是true
  application:
    name: search-service
  rabbitmq:
    host: 192.168.99.100
    username: guest
    password: quest

  data:
    elasticsearch:
      cluster-name: elasticsearch #默认名
      cluster-nodes: 127.0.0.1:9300 # 9300 默认端口
      repositories:
        enabled: true
  jackson:
    default-property-inclusion: non_null # 排除结果里面为null的字段，不让他显示到前台
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
