
spring:
  main:
    allow-bean-definition-overriding: true #在sprigboot2.1之前默认是true
  application:
    name: mall-page

  thymeleaf:
    cache: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
server:
  port: 8084